import type {
  BloqueOLote,
  CatalogoItem,
  ConfiguracionSistema,
  Equipo,
  Gasto,
  HistorialPago,
  InventarioMovimiento,
  Merma,
  ProduccionDiaria,
  ProduccionTrabajador,
  Producto,
  SystemLog,
  Trabajador,
  Venta,
  WorkshopTenant,
} from '../domain/entities/index.js'
import {
  TARIFAS_ACCION_DEFAULT,
  PRECIOS_M2_DEFAULT,
  SALARIOS_FIJOS_POR_ROL_DEFAULT,
} from './constants.js'

export const configuracionInicial: ConfiguracionSistema = {
  tarifasGlobales: { ...TARIFAS_ACCION_DEFAULT },
  salariosFijosPorRol: { ...SALARIOS_FIJOS_POR_ROL_DEFAULT },
  preciosM2: { ...PRECIOS_M2_DEFAULT },
  nombreEmpresa: 'Mármoles Elegance',
  email: 'info@marmoleselegance.com',
  telefono: '+52 555 123 4567',
  direccion: 'Av. Principal 123, Col. Centro, CDMX',
  notificacionesEmail: true,
  alertasStockBajo: true,
  reportesVentas: false,
}

export const bloquesYLotes: BloqueOLote[] = [
  {
    id: 'BL001',
    nombre: 'Bloque Carrara #1',
    tipo: 'Bloque',
    dimensionBase: '60x40',
    costo: 15000,
    costoTransporte: 1800,
    metrosComprados: 32.0,
    fechaIngreso: '2026-01-10',
    proveedor: 'Mármoles Italia S.A.',
    losasProducidas: 120,
    losasPerdidas: 8,
    metrosVendibles: 28.8,
    gananciaReal: 12500,
    estado: 'activo',
  },
  {
    id: 'BL002',
    nombre: 'Bloque Emperador #3',
    tipo: 'Bloque',
    dimensionBase: '40x40',
    costo: 12000,
    costoTransporte: 1400,
    metrosComprados: 26.5,
    fechaIngreso: '2026-01-05',
    proveedor: 'Canteras España',
    losasProducidas: 95,
    losasPerdidas: 12,
    metrosVendibles: 22.8,
    gananciaReal: 8500,
    estado: 'activo',
  },
  {
    id: 'LT001',
    nombre: 'Lote Crema Marfil #15',
    tipo: 'Lote',
    dimensionBase: '60x40',
    costo: 8500,
    costoTransporte: 900,
    metrosComprados: 52.0,
    fechaIngreso: '2026-01-15',
    proveedor: 'Distribuidora Nacional',
    losasProducidas: 200,
    losasPerdidas: 5,
    metrosVendibles: 48.0,
    gananciaReal: 15200,
    estado: 'activo',
  },
  {
    id: 'BL003',
    nombre: 'Bloque Calacatta Gold #2',
    tipo: 'Bloque',
    dimensionBase: '80x40',
    costo: 25000,
    costoTransporte: 2600,
    metrosComprados: 21.0,
    fechaIngreso: '2025-12-20',
    proveedor: 'Mármoles Italia S.A.',
    losasProducidas: 85,
    losasPerdidas: 3,
    metrosVendibles: 20.4,
    gananciaReal: 28000,
    estado: 'agotado',
  },
]

export const productos: Producto[] = [
  {
    id: 'P001',
    nombre: 'Piso Carrara 60x40 Pulido',
    tipo: 'Piso',
    estado: 'Pulido',
    ubicacion: 'almacen',
    dimension: '60x40',
    origenId: 'BL001',
    origenNombre: 'Bloque Carrara #1',
    cantidadLosas: 45,
    metrosCuadrados: 10.8,
    precioM2: 200,
    imagen: '/marble-carrara.jpg',
  },
  {
    id: 'P002',
    nombre: 'Plancha Carrara 80x40 Picado',
    tipo: 'Plancha',
    estado: 'Picado',
    ubicacion: 'almacen',
    dimension: '80x40',
    origenId: 'BL001',
    origenNombre: 'Bloque Carrara #1',
    cantidadLosas: 30,
    metrosCuadrados: 9.6,
    precioM2: 160,
    imagen: '/marble-carrara.jpg',
  },
  {
    id: 'P003',
    nombre: 'Piso Emperador 40x40 Pulido',
    tipo: 'Piso',
    estado: 'Pulido',
    ubicacion: 'almacen',
    dimension: '40x40',
    origenId: 'BL002',
    origenNombre: 'Bloque Emperador #3',
    cantidadLosas: 60,
    metrosCuadrados: 9.6,
    precioM2: 180,
    imagen: '/marble-emperador.jpg',
  },
  {
    id: 'P004',
    nombre: 'Piso Crema Marfil 60x40 Pulido',
    tipo: 'Piso',
    estado: 'Pulido',
    ubicacion: 'almacen',
    dimension: '60x40',
    origenId: 'LT001',
    origenNombre: 'Lote Crema Marfil #15',
    cantidadLosas: 80,
    metrosCuadrados: 19.2,
    precioM2: 200,
    imagen: '/marble-crema.jpg',
  },
  {
    id: 'P005',
    nombre: 'Plancha Calacatta 80x40 Pulido',
    tipo: 'Plancha',
    estado: 'Pulido',
    ubicacion: 'almacen',
    dimension: '80x40',
    origenId: 'BL003',
    origenNombre: 'Bloque Calacatta Gold #2',
    cantidadLosas: 20,
    metrosCuadrados: 6.4,
    precioM2: 320,
    imagen: '/marble-calacatta.jpg',
  },
  {
    id: 'P006',
    nombre: 'Piso Emperador 60x40 Escuadrado',
    tipo: 'Piso',
    estado: 'Escuadrado',
    ubicacion: 'almacen',
    dimension: '60x40',
    origenId: 'BL002',
    origenNombre: 'Bloque Emperador #3',
    cantidadLosas: 35,
    metrosCuadrados: 8.4,
    precioM2: 140,
    imagen: '/marble-emperador.jpg',
  },
]

export const catalogoItems: CatalogoItem[] = [
  {
    id: 'C001',
    nombre: 'Marmol Carrara Select 60x40',
    tipo: 'Piso',
    acabado: 'Pulido',
    dimension: '60x40',
    precioM2: 210,
    stockLosas: 120,
    destacado: true,
    descripcion:
      'Veta suave y elegante, ideal para salas, cocinas premium y proyectos residenciales.',
    imagen: '/marble-carrara.jpg',
    visible: true,
  },
  {
    id: 'C002',
    nombre: 'Calacatta Gold Signature 80x40',
    tipo: 'Plancha',
    acabado: 'Pulido',
    dimension: '80x40',
    precioM2: 340,
    stockLosas: 48,
    destacado: true,
    descripcion:
      'Alta demanda en barras y muros de impacto. Tonos dorados con vetas definidas.',
    imagen: '/marble-calacatta.jpg',
    visible: true,
  },
  {
    id: 'C003',
    nombre: 'Emperador Dark 60x40',
    tipo: 'Piso',
    acabado: 'Crudo',
    dimension: '60x40',
    precioM2: 170,
    stockLosas: 90,
    destacado: false,
    descripcion:
      'Acabado natural para proyectos boutique y espacios comerciales con alto trafico.',
    imagen: '/marble-emperador.jpg',
    visible: true,
  },
]

export const trabajadores: Trabajador[] = [
  {
    id: 'T001',
    nombre: 'Carlos Mendoza',
    email: 'carlos.mendoza@taller.com',
    telefono: '+52 555 123 4567',
    rol: 'Obrero',
    fechaIngreso: '2024-03-15',
    estado: 'activo',
    tarifasPersonalizadas: null,
    losasProducidas: 450,
    pagosTotales: 180000,
    bonosTotales: 5000,
    acumuladoPendiente: 9500,
  },
  {
    id: 'T002',
    nombre: 'Roberto Sánchez',
    email: 'roberto.sanchez@taller.com',
    telefono: '+52 555 234 5678',
    rol: 'Obrero',
    fechaIngreso: '2023-08-01',
    estado: 'activo',
    tarifasPersonalizadas: { picar: 400, pulir: 280, escuadrar: 100, resinar: 280 },
    losasProducidas: 620,
    pagosTotales: 155000,
    bonosTotales: 8000,
    acumuladoPendiente: 5600,
  },
  {
    id: 'T003',
    nombre: 'Miguel Ángel Torres',
    email: 'miguel.torres@taller.com',
    telefono: '+52 555 345 6789',
    rol: 'Jefe de Turno de Producción',
    fechaIngreso: '2022-01-10',
    estado: 'activo',
    usuario: 'produccion@marmol.local',
    contrasena: 'prod123',
    tarifasPersonalizadas: { picar: 420, pulir: 270, escuadrar: 120, resinar: 270 },
    losasProducidas: 890,
    pagosTotales: 310000,
    bonosTotales: 15000,
    acumuladoPendiente: 7600,
  },
  {
    id: 'T004',
    nombre: 'Fernando Ruiz',
    email: 'fernando.ruiz@taller.com',
    telefono: '+52 555 456 7890',
    rol: 'Administrador',
    fechaIngreso: '2021-06-20',
    estado: 'activo',
    usuario: 'admin@marmol.local',
    contrasena: 'admin123',
    tarifasPersonalizadas: { picar: 450, pulir: 300, escuadrar: 130, resinar: 300 },
    losasProducidas: 1200,
    pagosTotales: 420000,
    bonosTotales: 25000,
    acumuladoPendiente: 9750,
  },
  {
    id: 'T005',
    nombre: 'José García',
    email: 'jose.garcia@taller.com',
    telefono: '+52 555 567 8901',
    rol: 'Gestor de Ventas',
    fechaIngreso: '2025-02-01',
    estado: 'inactivo',
    usuario: 'ventas@marmol.local',
    contrasena: 'ventas123',
    tarifasPersonalizadas: null,
    losasProducidas: 150,
    pagosTotales: 15000,
    bonosTotales: 0,
    acumuladoPendiente: 0,
  },
]

export const equipos: Equipo[] = [
  { id: 'EQ001', nombre: 'Cortadora Norte 01', tipo: 'Cortadora', codigoInterno: 'COR-01', estado: 'activo', notas: 'Disco nuevo instalado' },
  { id: 'EQ002', nombre: 'Cortadora Norte 02', tipo: 'Cortadora', codigoInterno: 'COR-02', estado: 'mantenimiento', notas: 'Revision de motor programada' },
  { id: 'EQ003', nombre: 'Pulidora Central 01', tipo: 'Pulidora', codigoInterno: 'PUL-01', estado: 'activo', notas: 'Operacion estable' },
  { id: 'EQ004', nombre: 'Pulidora Central 02', tipo: 'Pulidora', codigoInterno: 'PUL-02', estado: 'activo', notas: 'Disponible para turno tarde' },
  { id: 'EQ005', nombre: 'Escuadradora Este 01', tipo: 'Escuadradora', codigoInterno: 'ESC-01', estado: 'activo', notas: 'Alineada y calibrada' },
  { id: 'EQ006', nombre: 'Escuadradora Este 02', tipo: 'Escuadradora', codigoInterno: 'ESC-02', estado: 'inactivo', notas: 'Pendiente de repuesto' },
]

export const produccionDiaria: ProduccionDiaria[] = [
  {
    id: 'PG001',
    fecha: '2026-01-28',
    origenId: 'BL001',
    origenNombre: 'Bloque Carrara #1',
    tipo: 'Piso',
    dimension: '60x40',
    cantidadPicar: 15,
    cantidadPulir: 20,
    cantidadEscuadrar: 0,
    cantidadResinar: 0,
    totalLosas: 35,
    totalM2: 8.4,
    detallesAcciones: [
      { id: 'PGA001', accion: 'picar', trabajadorId: 'T001', trabajadorNombre: 'Carlos Mendoza', equipoId: 'EQ001', equipoNombre: 'Cortadora Norte 01', cantidadLosas: 15, metrosCuadrados: 3.6 },
      { id: 'PGA002', accion: 'pulir', trabajadorId: 'T002', trabajadorNombre: 'Roberto Sánchez', equipoId: 'EQ003', equipoNombre: 'Pulidora Central 01', cantidadLosas: 20, metrosCuadrados: 4.8 },
    ],
  },
  {
    id: 'PG002',
    fecha: '2026-01-28',
    origenId: 'BL002',
    origenNombre: 'Bloque Emperador #3',
    tipo: 'Piso',
    dimension: '40x40',
    cantidadPicar: 0,
    cantidadPulir: 0,
    cantidadEscuadrar: 25,
    cantidadResinar: 0,
    totalLosas: 25,
    totalM2: 4,
    detallesAcciones: [
      { id: 'PGA003', accion: 'escuadrar', trabajadorId: 'T003', trabajadorNombre: 'Miguel Ángel Torres', equipoId: 'EQ005', equipoNombre: 'Escuadradora Este 01', cantidadLosas: 25, metrosCuadrados: 4 },
    ],
  },
  {
    id: 'PG003',
    fecha: '2026-01-27',
    origenId: 'LT001',
    origenNombre: 'Lote Crema Marfil #15',
    tipo: 'Piso',
    dimension: '60x40',
    cantidadPicar: 0,
    cantidadPulir: 35,
    cantidadEscuadrar: 30,
    cantidadResinar: 0,
    totalLosas: 65,
    totalM2: 15.6,
    detallesAcciones: [
      { id: 'PGA004', accion: 'pulir', trabajadorId: 'T004', trabajadorNombre: 'Fernando Ruiz', equipoId: 'EQ004', equipoNombre: 'Pulidora Central 02', cantidadLosas: 35, metrosCuadrados: 8.4 },
      { id: 'PGA005', accion: 'escuadrar', trabajadorId: 'T001', trabajadorNombre: 'Carlos Mendoza', equipoId: 'EQ005', equipoNombre: 'Escuadradora Este 01', cantidadLosas: 30, metrosCuadrados: 7.2 },
    ],
  },
  {
    id: 'PG004',
    fecha: '2026-01-26',
    origenId: 'BL002',
    origenNombre: 'Bloque Emperador #3',
    tipo: 'Plancha',
    dimension: '80x40',
    cantidadPicar: 12,
    cantidadPulir: 0,
    cantidadEscuadrar: 0,
    cantidadResinar: 0,
    totalLosas: 12,
    totalM2: 3.84,
  },
]

export const produccionTrabajadores: ProduccionTrabajador[] = [
  { id: 'PD001', fecha: '2026-01-28', trabajadorId: 'T001', trabajadorNombre: 'Carlos Mendoza', accion: 'picar', origenId: 'BL001', origenNombre: 'Bloque Carrara #1', tipo: 'Piso', dimension: '60x40', cantidadLosas: 15, pagoPorLosa: 400, pagoTotal: 6000, bono: 500, pagoFinal: 6500, pagado: false },
  { id: 'PD002', fecha: '2026-01-28', trabajadorId: 'T002', trabajadorNombre: 'Roberto Sánchez', accion: 'pulir', origenId: 'BL001', origenNombre: 'Bloque Carrara #1', tipo: 'Piso', dimension: '60x40', cantidadLosas: 20, pagoPorLosa: 280, pagoTotal: 5600, bono: 0, pagoFinal: 5600, pagado: false },
  { id: 'PD003', fecha: '2026-01-28', trabajadorId: 'T003', trabajadorNombre: 'Miguel Ángel Torres', accion: 'escuadrar', origenId: 'BL002', origenNombre: 'Bloque Emperador #3', tipo: 'Piso', dimension: '40x40', cantidadLosas: 25, pagoPorLosa: 120, pagoTotal: 3000, bono: 300, pagoFinal: 3300, pagado: false },
  { id: 'PD004', fecha: '2026-01-27', trabajadorId: 'T001', trabajadorNombre: 'Carlos Mendoza', accion: 'escuadrar', origenId: 'LT001', origenNombre: 'Lote Crema Marfil #15', tipo: 'Piso', dimension: '60x40', cantidadLosas: 30, pagoPorLosa: 100, pagoTotal: 3000, bono: 0, pagoFinal: 3000, pagado: false },
  { id: 'PD005', fecha: '2026-01-27', trabajadorId: 'T004', trabajadorNombre: 'Fernando Ruiz', accion: 'pulir', origenId: 'LT001', origenNombre: 'Lote Crema Marfil #15', tipo: 'Piso', dimension: '60x40', cantidadLosas: 35, pagoPorLosa: 300, pagoTotal: 10500, bono: 1000, pagoFinal: 11500, pagado: true },
  { id: 'PD006', fecha: '2026-01-26', trabajadorId: 'T003', trabajadorNombre: 'Miguel Ángel Torres', accion: 'picar', origenId: 'BL002', origenNombre: 'Bloque Emperador #3', tipo: 'Plancha', dimension: '80x40', cantidadLosas: 12, pagoPorLosa: 420, pagoTotal: 5040, bono: 0, pagoFinal: 5040, pagado: true },
]

export const mermas: Merma[] = [
  { id: 'M001', fecha: '2026-01-28', origenId: 'BL001', origenNombre: 'Bloque Carrara #1', tipo: 'Piso', dimension: '60x40', cantidadLosas: 2, metrosCuadrados: 0.48, motivo: 'Partida al picar', observaciones: 'Vetas internas causaron fractura' },
  { id: 'M002', fecha: '2026-01-27', origenId: 'BL002', origenNombre: 'Bloque Emperador #3', tipo: 'Piso', dimension: '40x40', cantidadLosas: 2, metrosCuadrados: 0.32, motivo: 'Partida al pulir', observaciones: 'Presión excesiva en el proceso' },
  { id: 'M003', fecha: '2026-01-25', origenId: 'LT001', origenNombre: 'Lote Crema Marfil #15', tipo: 'Piso', dimension: '60x40', cantidadLosas: 1, metrosCuadrados: 0.24, motivo: 'Recorte aprovechable', observaciones: 'Recorte de bordes para escuadrar' },
  { id: 'M004', fecha: '2026-01-24', origenId: 'BL003', origenNombre: 'Bloque Calacatta Gold #2', tipo: 'Plancha', dimension: '80x40', cantidadLosas: 2, metrosCuadrados: 0.64, motivo: 'Defecto de material', observaciones: 'Grieta natural descubierta al procesar' },
]

export const ventas: Venta[] = [
  { id: 'V001', productoId: 'P001', productoNombre: 'Piso Carrara 60x40 Pulido', cantidadM2: 5.5, metrosPorDimension: { '40x40': 0, '60x40': 5.5, '80x40': 0 }, precioM2: 200, descuento: 5, fondoOperativo: 50, subtotal: 1100, total: 1095, clienteNombre: 'Constructora Moderna S.A.', clienteEmail: 'compras@constructoramoderna.com', clienteTelefono: '+52 555 111 2222', fecha: '2026-01-28', estado: 'completada' },
  { id: 'V002', productoId: 'P005', productoNombre: 'Plancha Calacatta 80x40 Pulido', cantidadM2: 3.2, metrosPorDimension: { '40x40': 0, '60x40': 0, '80x40': 3.2 }, precioM2: 320, descuento: 0, fondoOperativo: 100, subtotal: 1024, total: 1124, clienteNombre: 'Diseños Interiores Premium', clienteEmail: 'pedidos@disenospremium.com', clienteTelefono: '+52 555 333 4444', fecha: '2026-01-27', estado: 'completada' },
  { id: 'V003', productoId: 'P004', productoNombre: 'Piso Crema Marfil 60x40 Pulido', cantidadM2: 12.0, metrosPorDimension: { '40x40': 0, '60x40': 12.0, '80x40': 0 }, precioM2: 200, descuento: 10, fondoOperativo: 75, subtotal: 2400, total: 2235, clienteNombre: 'Residencial Los Pinos', clienteEmail: 'admin@lospinos.com', clienteTelefono: '+52 555 555 6666', fecha: '2026-01-26', estado: 'pendiente' },
  { id: 'V004', productoId: 'P003', productoNombre: 'Piso Emperador 40x40 Pulido', cantidadM2: 8.0, metrosPorDimension: { '40x40': 8.0, '60x40': 0, '80x40': 0 }, precioM2: 180, descuento: 0, fondoOperativo: 60, subtotal: 1440, total: 1500, clienteNombre: 'Hotel Grand Palace', clienteEmail: 'mantenimiento@grandpalace.com', clienteTelefono: '+52 555 777 8888', fecha: '2026-01-25', estado: 'completada' },
]

export const historialPagos: HistorialPago[] = [
  { id: 'HP001', trabajadorId: 'T004', trabajadorNombre: 'Fernando Ruiz', fecha: '2026-01-27', produccionIds: ['PD005'], montoAcciones: 10500, montoBonos: 1000, bonoExtra: 500, motivoBonoExtra: 'Excelente trabajo en lote especial', totalPagado: 12000, observaciones: 'Pago semanal' },
  { id: 'HP002', trabajadorId: 'T003', trabajadorNombre: 'Miguel Ángel Torres', fecha: '2026-01-26', produccionIds: ['PD006'], montoAcciones: 5040, montoBonos: 0, bonoExtra: 0, motivoBonoExtra: '', totalPagado: 5040, observaciones: 'Pago por producción del día' },
]

export const logsSistema: SystemLog[] = [
  { id: 'LOG001', fecha: '2026-02-03 08:15', usuario: 'admin@marmol.local', accion: 'Creo bloque', modulo: 'Bloques', descripcion: 'Registro de Bloque Carrara #4', nivel: 'info' },
  { id: 'LOG002', fecha: '2026-02-03 09:05', usuario: 'produccion@marmol.local', accion: 'Registro produccion', modulo: 'Produccion', descripcion: 'Registro de losas pulidas (20) en Bloque Carrara #1', nivel: 'info' },
  { id: 'LOG003', fecha: '2026-02-02 16:40', usuario: 'ventas@marmol.local', accion: 'Venta creada', modulo: 'Ventas', descripcion: 'Venta V004 creada para Hotel Grand Palace', nivel: 'alerta' },
  { id: 'LOG004', fecha: '2026-02-02 18:10', usuario: 'admin@marmol.local', accion: 'Cambio de estado', modulo: 'Bloques', descripcion: 'Bloque Calacatta Gold #2 marcado como agotado', nivel: 'info' },
  { id: 'LOG005', fecha: '2026-02-01 13:22', usuario: 'produccion@marmol.local', accion: 'Merma registrada', modulo: 'Mermas', descripcion: 'Merma por partida al pulir (0.32 m2)', nivel: 'alerta' },
  { id: 'LOG006', fecha: '2026-02-01 14:05', usuario: 'admin@marmol.local', accion: 'Error de registro', modulo: 'Inventario', descripcion: 'Intento de registrar producto sin origen valido', nivel: 'error' },
]

export const inventarioMovimientos: InventarioMovimiento[] = []

export const gastos: Gasto[] = [
  {
    id: 'G001',
    fecha: '2026-02-24',
    costo: 1400,
    tipo: 'Transporte',
    flujo: 'Inventario',
    descripcion: 'Traslado de bloque BL002 desde proveedor principal.',
    encargado: 'Fernando Ruiz',
  },
  {
    id: 'G002',
    fecha: '2026-02-25',
    costo: 950,
    tipo: 'Servicios',
    flujo: 'Produccion',
    descripcion: 'Pago de energia electrica en turno extendido de pulido.',
    encargado: 'Miguel Angel Torres',
  },
  {
    id: 'G003',
    fecha: '2026-02-27',
    costo: 650,
    tipo: 'Mantenimiento',
    flujo: 'Produccion',
    descripcion: 'Cambio de disco y ajuste preventivo de cortadora.',
    encargado: 'Carlos Mendoza',
  },
]

export const workshops: WorkshopTenant[] = [
  { id: 'TLR-001', nombre: 'Taller Central CDMX', ciudad: 'Ciudad de Mexico', direccion: 'Av. Principal 123, Col. Centro', encargado: 'Fernando Ruiz', telefono: '+52 555 456 7890', correo: 'cdmx@marmol.local', estado: 'activo', empleados: 18, capacidadM2Mes: 1600, ventasMes: 245000, produccionMesM2: 1280, margenOperativo: 0.26, ordenesActivas: 14, ultimaActualizacion: '2026-02-05' },
  { id: 'TLR-002', nombre: 'Taller Guadalajara', ciudad: 'Guadalajara', direccion: 'Carr. Chapala 980, Zona Industrial', encargado: 'Lucia Herrera', telefono: '+52 333 210 9988', correo: 'gdl@marmol.local', estado: 'activo', empleados: 12, capacidadM2Mes: 1100, ventasMes: 162000, produccionMesM2: 940, margenOperativo: 0.22, ordenesActivas: 9, ultimaActualizacion: '2026-02-04' },
  { id: 'TLR-003', nombre: 'Taller Monterrey', ciudad: 'Monterrey', direccion: 'Av. Lazaro Cardenas 1340, Sur', encargado: 'Marco Salinas', telefono: '+52 818 555 3020', correo: 'mty@marmol.local', estado: 'en-implementacion', empleados: 9, capacidadM2Mes: 780, ventasMes: 98000, produccionMesM2: 520, margenOperativo: 0.18, ordenesActivas: 6, ultimaActualizacion: '2026-02-02' },
]
